# Generated by Django 3.2.5 on 2021-07-21 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codelibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelibrary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='codelibrary',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
